#ifndef WJR_ARCH_X86_UTF8_UTF8_HPP__
#define WJR_ARCH_X86_UTF8_UTF8_HPP__

#include <wjr/arch/x86/simd/simd.hpp>

#if WJR_HAS_SIMD(SSE2)
    #define WJR_HAS_BUILTIN_UTF8_CHECK_UNICODE WJR_HAS_DEF
    #define WJR_HAS_BUILTIN_UTF8_UNICODE_TO_UTF8 WJR_HAS_DEF
#endif

#endif // WJR_ARCH_X86_UTF8_UTF8_HPP__