repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        args: [--dry-run, --Werror, --style=file]
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
        exclude: ^(third-party|build(?:_[^/]*)?)/