#ifndef WJR_ARCH_X86_JSON_LEXER_HPP__
#define WJR_ARCH_X86_JSON_LEXER_HPP__

#include <wjr/config.hpp>

WJR_ENSURE_CONFIG()

#if WJR_HAS_SIMD(SSSE3)
    #define WJR_HAS_BUILTIN_JSON_LEXER_READER_READ_BUF WJR_HAS_DEF
    #define WJR_HAS_BUILTIN_JSON_MINIFY_BUF WJR_HAS_DEF
#endif

#endif // WJR_ARCH_X86_JSON_LEXER_HPP__