var class__base_8hpp =
[
    [ "wjr::enable_default_constructor_t", "structwjr_1_1enable__default__constructor__t.html", "structwjr_1_1enable__default__constructor__t" ],
    [ "wjr::enable_default_constructor_base< Enable, Tag >", "structwjr_1_1enable__default__constructor__base.html", "structwjr_1_1enable__default__constructor__base" ],
    [ "wjr::enable_default_constructor_base< false, Tag >", "structwjr_1_1enable__default__constructor__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__default__constructor__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_copy_constructor_base< Enable, Tag >", "structwjr_1_1enable__copy__constructor__base.html", "structwjr_1_1enable__copy__constructor__base" ],
    [ "wjr::enable_copy_constructor_base< false, Tag >", "structwjr_1_1enable__copy__constructor__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__copy__constructor__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_move_constructor_base< Enable, Tag >", "structwjr_1_1enable__move__constructor__base.html", "structwjr_1_1enable__move__constructor__base" ],
    [ "wjr::enable_move_constructor_base< false, Tag >", "structwjr_1_1enable__move__constructor__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__move__constructor__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_copy_assignment_base< Enable, Tag >", "structwjr_1_1enable__copy__assignment__base.html", "structwjr_1_1enable__copy__assignment__base" ],
    [ "wjr::enable_copy_assignment_base< false, Tag >", "structwjr_1_1enable__copy__assignment__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__copy__assignment__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_move_assignment_base< Enable, Tag >", "structwjr_1_1enable__move__assignment__base.html", "structwjr_1_1enable__move__assignment__base" ],
    [ "wjr::enable_move_assignment_base< false, Tag >", "structwjr_1_1enable__move__assignment__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__move__assignment__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_destructor_base< Enable, Tag >", "structwjr_1_1enable__destructor__base.html", "structwjr_1_1enable__destructor__base" ],
    [ "wjr::enable_destructor_base< false, Tag >", "structwjr_1_1enable__destructor__base_3_01false_00_01_tag_01_4.html", "structwjr_1_1enable__destructor__base_3_01false_00_01_tag_01_4" ],
    [ "wjr::enable_special_members_base< Default, Destructor, Copy, Move, CopyAssign, MoveAssign, Tag >", "structwjr_1_1enable__special__members__base.html", "structwjr_1_1enable__special__members__base" ],
    [ "wjr::enable_base_identity_t< I, T >", "structwjr_1_1enable__base__identity__t.html", null ],
    [ "wjr::control_copy_ctor_base< _Mybase >", "structwjr_1_1control__copy__ctor__base.html", "structwjr_1_1control__copy__ctor__base" ],
    [ "wjr::control_move_ctor_base< _Mybase >", "structwjr_1_1control__move__ctor__base.html", "structwjr_1_1control__move__ctor__base" ],
    [ "wjr::control_copy_assign_base< _Mybase >", "structwjr_1_1control__copy__assign__base.html", "structwjr_1_1control__copy__assign__base" ],
    [ "wjr::control_move_assign_base< _Mybase >", "structwjr_1_1control__move__assign__base.html", "structwjr_1_1control__move__assign__base" ],
    [ "control_special_members_base", "class__base_8hpp.html#af1742053969bc4eb4e1a945213680d3f", null ],
    [ "enable_copy_move_base", "class__base_8hpp.html#a00a2172355f3796ea984acd2943cf518", null ],
    [ "enable_special_members_of_args_base", "class__base_8hpp.html#ad83ed83dc32a68c6abd2d79bf5c130fb", null ],
    [ "enable_trivially_special_members_of_args_base", "class__base_8hpp.html#adac894b9b98a2715b8f9e52897872ba5", null ],
    [ "noncopyable", "class__base_8hpp.html#a53edc7ccf2397ee54717fca84217ddb5", null ],
    [ "nonmoveable", "class__base_8hpp.html#af03379587ea4a071b01fc7acb166c61c", null ],
    [ "enable_default_constructor", "class__base_8hpp.html#a3a11cdbc4a8173a936d2a0721a23ad45", null ]
];