#ifndef WJR_PREPROCESSOR_HAS_HPP__
#define WJR_PREPROCESSOR_HAS_HPP__

#define WJR_HAS_INLINE_ASM 0
#define WJR_HAS_INT128 0
#define WJR_HAS_INT128_DIV 0
#define WJR_HAS_CONSTANT_EVALUATED 0
#define WJR_HAS_CONSTANT_P 0

#endif // ! WJR_PREPROCESSOR_HAS_HPP__